name: Cargo Build

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'BRANCH'
        required: true
        default: 'main'
      URL:
        description: 'URL'
        required: true
        default: ''

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v4

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install rust

    - name: Clone
      run: |
        git clone ${{ github.event.inputs.URL }} -b ${{ github.event.inputs.BRANCH }} ./build
        cd build

    - name: Building recovery
      run: |
        cargo build --release 

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: | 
          workspace/out/target/product/build/target/release/build
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
